apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: v1
kind: Service
metadata:
  name: brotomotif
  namespace: production
spec:
  selector:
    app: brotomotif
  ports:
  - port: 80
    name: http
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brotomotif
  namespace: production
spec:
  selector:
    matchLabels:
      app: brotomotif
  strategy:
    type: RollingUpdate
  template: #Template for container
    metadata:
      labels:
        app: wooless
    spec:
      containers:
      - name: brotomotif
        image:  asia.gcr.io/$PROJECT_ID/production/wooless:$SHORT_SHA
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: brotomotif
        resources:
          requests:
            cpu: 50m

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: brotomotif
  namespace: production
spec:
  maxReplicas: 25
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: brotomotif
  targetCPUUtilizationPercentage: 100


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brotomotif
  annotations:
    kubernetes.io/ingress.global-static-ip-name: brotomotif
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: brotomotif
            port:
              number: 80



