apiVersion: v1
kind: Namespace
metadata:
  name: production

---
apiVersion: v1
kind: Service
metadata:
  name: brotomotif
  namespace: production
  labels:
    app: brotomotif
spec:
  selector:
    app: brotomotif
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  type: NodePort


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brotomotif
  namespace: production
spec:
  selector:
    matchLabels:
      app: brotomotif
  strategy:
    type: RollingUpdate
  template: #Template for container
    metadata:
      labels:
        app: brotomotif
    spec:
      containers:
      - name: brotomotif
        image:  asia.gcr.io/$PROJECT_ID/production/brotomotif:$SHORT_SHA
        imagePullPolicy: Always
        ports: 
        - containerPort: 3000
          name: brotomotif
        resources:
          requests:
            cpu: 50m

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: brotomotif
  namespace: production
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: brotomotif
  targetCPUUtilizationPercentage: 100



